name: Release C++ CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: '1.3.231.1'  # Specify the version you need
        install_runtime: true
        cache: true
        stripdown: true

    - name: Verify Vulkan installation
      run: |
        echo "Vulkan SDK installed at ${{ env.VULKAN_SDK }}"
        dir ${{ env.VULKAN_SDK }}

    - name: Download prebuilt GLFW binaries
      run: |
        curl -L https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.bin.WIN64.zip -o glfw.zip
        tar -xf glfw.zip -C vendor

    - name: Install GLM
      run: |
        curl -L -o glm.zip https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
        unzip glm.zip -d C:/glm
        echo "GLM installed at C:/glm"
    
    - name: Download libsndfile
      run: |
        curl -L -o libsndfile.zip https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip
        unzip libsndfile.zip -d vendor

    - name: Set up environment variables
      run: |
        echo "LIBSNDFILE_DIR=$(pwd)/vendor/libsndfile-1.2.2-win64" >> $GITHUB_ENV
        echo "PATH=$(pwd)/vendor/libsndfile-1.2.2-win64/bin:$PATH" >> $GITHUB_ENV

    - name: Build GLSL Shaders
      run: |
        mkdir -p build/shaders
        $shaderFiles = Get-ChildItem -Path shaders -Include *.vert,*.frag -Recurse
        foreach ($file in $shaderFiles) {
          ${{ env.VULKAN_SDK }}/Bin/glslc.exe $file.FullName -o build/shaders/$($file.Name).spv
        }
        echo "GLSL shaders compiled to SPIR-V"

    - name: List vendor directory
      run: ls -l vendor

    - name: Configure CMake
      run: |
        cmake -S . -B build -DVULKAN_SDK_PATH="${{ env.VULKAN_SDK }}" -DGLM_PATH="C:\glm\glm" -DGLFW_PATH="vendor\glfw-3.3.8.bin.WIN64" -DGLFW_LIBRARY="C:\ProgramData\chocolatey\lib\glfw\lib" -DLIBSNDFILE_PATH="vendor\libsndfile-1.2.2-win64" -DPORTAUDIO_ENABLE=true

    - name: Build
      run: cmake --build build --config Release
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev libglm-dev libsndfile1-dev libglfw3-dev portaudio19-dev

    - name: Configure and Build
      run: |
        cmake -S . -B build
        cmake --build build
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        curl -sSf https://sdk.lunarg.com/sdk/download/1.3.231.1/mac/vulkansdk-macos-1.3.231.1.dmg -o vulkan.dmg
        hdiutil attach vulkan.dmg -nobrowse -plist | xpath '/plist/key[.="volumes"]/following-sibling::array/dict[1]/key[.="mount-point"]/following-sibling::string' # 2>/dev/null | xargs -I{} sudo hdiutil detach {}

        # Install other dependencies using Homebrew
        brew install glfw
        brew install glm
        brew install portaudio
        brew install libsndfile
        brew install make
        brew install gcc
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.204.1
        cache: true
    - name: List Vulkan SDK install dir
      run: ls $VULKAN_SDK

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DVULKAN_SDK_PATH=$VULKAN_SDK -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_C_COMPILER=/usr/bin/gcc -DAPPLE=1
        cmake --build .