name: Release C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule init

    - name: Update submodules
      run: git submodule update --recursive --remote --verbose

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install Vulkan SDK
      run: |
        choco install vulkan-sdk
        setx VULKAN_SDK "C:\Program Files (x86)\VulkanSDK\1.2.182.0"

    - name: Install GLFW
      run: choco install glfw3

    - name: List vendor directory
      run: ls -l vendor

    - name: Configure CMake
      run: |
        cmake -S . -B build -DVULKAN_SDK_PATH="%VULKAN_SDK%" -DGLM_PATH="%VULKAN_SDK%\Include\glm" -DGLFW_PATH="C:\ProgramData\chocolatey\lib\glfw3" -DGLFW_LIBRARY="C:\ProgramData\chocolatey\lib\glfw\lib"

    - name: Build
      run: cmake --build build --config Release

