name: Release C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Download Vulkan SDK
      run: |
        curl -L https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe -o vulkan-sdk.exe
        vulkan-sdk.exe --accept-licenses --default-answer --confirm-command install
        setx VULKAN_SDK "C:/VulkanSDK/1.2.198.1/"

    - name: Download prebuilt GLFW binaries
      run: |
        curl -L https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.bin.WIN64.zip -o glfw.zip
        tar -xf glfw.zip -C vendor

    - name: List vendor directory
      run: ls -l vendor

    - name: Configure CMake
      run: |
        cmake -S . -B build -DVULKAN_SDK_PATH="%VULKAN_SDK%" -DGLM_PATH="%VULKAN_SDK%\Include\glm" -DGLFW_PATH="vendor\glfw-3.3.8.bin.WIN64" -DGLFW_LIBRARY="C:\ProgramData\chocolatey\lib\glfw\lib"

    - name: Build
      run: cmake --build build --config Release

